# Generated by Django 2.2.5 on 2019-09-29 10:41

from django.db import migrations, models
import django.db.models.deletion
import interface.fields


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_packaging_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='packaging',
            name='label',
            field=interface.fields.EANField(verbose_name='EAN code'),
        ),
        migrations.CreateModel(
            name='BrandEAN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_label', models.CharField(help_text='First 7 numbers of the EAN, which indicate the brand', max_length=7)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Brand')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='generic_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='interface.GenericProduct'),
            preserve_default=False,
        ),
    ]
