# Generated by Django 2.2.5 on 2019-09-29 10:47

from django.db import migrations, models
import interface.fields


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_auto_20190929_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(help_text="Brand name, for example 'Douwe Egberts'.", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='brandean',
            name='brand_label',
            field=models.CharField(help_text='First 7 numbers of the EAN, which indicate the brand', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='label',
            field=interface.fields.EANField(unique=True, verbose_name='EAN code'),
        ),
    ]
