# Generated by Django 2.2.6 on 2019-10-20 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_auto_20191008_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='generic_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='interface.GenericProduct'),
        ),
    ]
