# Generated by Django 2.2.6 on 2019-10-20 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_auto_20191020_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='count',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of product per package (e.g. sixpack).', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
