# Generated by Django 2.2.6 on 2019-10-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_auto_20191020_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
