# Generated by Django 2.2.6 on 2019-10-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_auto_20191020_1254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrandEAN',
        ),
    ]
